# Generated by Django 5.1.1 on 2025-05-02 15:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='encrypted_private_key',
        ),
        migrations.AddField(
            model_name='wallet',
            name='_private_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36),
        ),
        migrations.AddField(
            model_name='wallet',
            name='name',
            field=models.CharField(default='Main Wallet', max_length=100),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('to_address', models.CharField(max_length=42)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
        ),
    ]
